spring.application.name=api-clientes
server.port=8081

datasource.host=jdbc:postgresql://localhost:5432/db-api-clientes
datasource.user=postgres
datasource.pass=Flv@1997

#Permissoes de CORS
cors.enabled=http://localhost:4200