CREATE TABLE clientes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE
);
CREATE TABLE enderecos (
    id SERIAL PRIMARY KEY,
    cliente_id INTEGER NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(255),
    bairro VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

ALTER TABLE clientes
ADD COLUMN STATUS INTEGER DEFAULT 1;

ALTER TABLE clientes
ADD COLUMN DATAHORACADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE clientes
ADD COLUMN DATAHORAEXCLUSAO TIMESTAMP null;